<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--<TargetFrameworks>
      net10.0-windows10.0.19041.0
    </TargetFrameworks>-->
    <TargetFrameworks>
      net10.0-android36.0;
      net10.0-windows10.0.19041.0
    </TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>AndroidMic</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Display name -->
    <ApplicationTitle>AndroidMic</ApplicationTitle>

    <!-- App Identifier -->
    <ApplicationId>com.bvi.androidmic</ApplicationId>
    <ApplicationIdGuid>A1B2C3D4-E5F6-7890-ABCD-EF1234567890</ApplicationIdGuid>

    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">34.0</SupportedOSPlatformVersion>
    <MinimumRequiredVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</MinimumRequiredVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
    <WindowsPackageType>MSIX</WindowsPackageType>
  </PropertyGroup>
  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.20" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.20" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EspSpectrum.Core\EspSpectrum.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="appsettings.json" />
  </ItemGroup>

  <!-- Windows specific settings -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
  </PropertyGroup>

  <!-- Android specific settings -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
    <AotAssemblies>true</AotAssemblies>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Debug'">
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AotAssemblies>false</AotAssemblies>
    <AndroidLinkMode>None</AndroidLinkMode>
    <EmbedAssembliesIntoApk>false</EmbedAssembliesIntoApk>
    <!-- Fast builds, easier debugging -->
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidPackageFormat>aab</AndroidPackageFormat>
    <!-- Optional for maximum performance, but very slow builds: -->
    <AndroidEnableLLVM>true</AndroidEnableLLVM>

    <!-- Signature avec clé UPLOAD -->
    <AndroidSigningKeyStore>upload-keystore.jks</AndroidSigningKeyStore>
    <AndroidSigningStorePass>$(ANDROID_KEYSTORE_PASSWORD)</AndroidSigningStorePass>
    <AndroidSigningKeyAlias>upload</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>$(ANDROID_KEY_PASSWORD)</AndroidSigningKeyPass>
  </PropertyGroup>

</Project>